### ISSUE TITLE
As a developer, I would like to see API documentation

### ISSUE THREAD

**Issue by ultrasaurus** [dlapiduz/govcode.org#47]

**Comment by dlapiduz** [comment]
Here is the information about the API:
- The endpoint is currently public at https://api.govcode.org
- The URLs are here https://github.com/dlapiduz/govcode.org/blob/master/govcoded/main.go#L33-L51

Basically these are the urls:
- `https://api.govcode.org/`
- `https://api.govcode.org/repos/`
- `https://api.govcode.org/repos/:name`
- `https://api.govcode.org/orgs/`
- `https://api.govcode.org/orgs/:name`
- `https://api.govcode.org/users/`
- `https://api.govcode.org/users/:id`
- `https://api.govcode.org/stats/`
- `https://api.govcode.org/issues/?perPage=10&page=2&repoId=20&orgId=200&languages=python&organizations=18F&state=open&label=help`

**Comment by ultrasaurus** [comment]
is this fixed by:  https://github.com/dlapiduz/govcode.org/pull/50  ?

**Comment by dlapiduz** [comment]
@ultrasaurus I think so...
