### ISSUE TITLE
Which government is this for?

### ISSUE THREAD

**Issue by jawz101** [dlapiduz/govcode.org#55]
There are many countries with governments.  Which countries use these projects?  What are these projects.  Who the heck is dlapiduz?  That doesn't sound like the name of an official governmenty sounding project maintainer.

Are these forks from other legit gov't things?  Are these big projects like the Office of Veterans Affairs VIstA medical record system?  Is this just a bunch of widget/library things you're hosting for doing random junk?  It doesn't look like significant stuff to a normal person.

**Comment by dhcole** [comment]
Leaving aside the deep philosophical dualist questions about who are we and how do we even know, this is currently just a catalog of projects from users affiliated US federal government accounts. You're welcome to fork and use for any government you like, or build your own. I'd suggest Nutopia, where only cosmic laws apply. :pensive: 

Productive conversation tracked here: #15

**Comment by jawz101** [comment]
Sorry about that.  I can be a bit rude sometimes.
I do think I want to help so I'll keep an eye on this repo because it's a great idea.
